# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hold_arm
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link_to_arm1_link1
    - arm1_link1_to_link2
    - arm1_link2_to_link3
    - arm1_link3_to_link4
    - arm1_link4_to_left_gripper
    - base_link_to_arm2_link1
    - arm2_link1_to_link2
    - arm2_link2_to_link3
    - arm2_link3_to_link4
    - base_link_to_wheel1
    - base_link_to_wheel2
    - base_link_to_wheel3
    - base_link_to_wheel4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: hold_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_arm1_link1
      - arm1_link1_to_link2
      - arm1_link2_to_link3
      - arm1_link3_to_link4
      - arm1_link4_to_left_gripper
  - name: cut_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_arm2_link1
      - arm2_link1_to_link2
      - arm2_link2_to_link3
      - arm2_link3_to_link4
  - name: hold_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      arm1_link4_to_left_gripper
  - name: cut_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      arm2_link3_to_link4